baseURL = "https://datakubism.com/"
languageCode = "en-us"
title = "dataKubism"

theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Services"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Projects"
    URL = "portfolio"
    weight = 4

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 5

#    [[menu.nav]]
#    name = "Pricing"
#    URL = "pricing"
#    weight = 6

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "images/logos/datakubism.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Unlock the Power of Your Data"
author = "datakubism"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/backgrounds/main_background.jpg"
    icon = "tf-ion-code-working"
    heading = "unlock the power of your data"
    content= "Using cutting-edge machine learning techniques and an agile ultra-flexible workflow, we can help you derive true business value through data analyics."
    btn = true
    btnText="Explore Us"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "Powerful Machine Learning and Actionable Insights"
    content = "Our services cover the entire end-to-end lifespan of an analytics project - from scoping and problem identification, through data collection and feature engineering, model development and validation, to deployment in production."
    btnURL = "#contact-us"
    btnText = "Start a project with us"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/wall.jpg"
        [[params.counter.counterItem]]
        title = "Projects completed"
        icon = "tf-ion-battery-full"
        count = "53"

        [[params.counter.counterItem]]
        title = "Models validated"
        icon = "tf-ion-thumbsup"
        count = "12"

        [[params.counter.counterItem]]
        title = "Microservices deployed"
        icon = "tf-ion-checkmark"
        count = "23"

        [[params.counter.counterItem]]
        title = "Hours spent coding"
        icon = "tf-ion-laptop"
        count = "25000"

    # footer
    [params.footer]
        copyright = "dataKubism Team"
        copyrightURL = "https://www.datakubism.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "https://www.facebook.com/ocenimebg/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        url = "https://www.linkedin.com/company/28667141"
